
// this is the fist account generated by testrpc when run with the '--deterministic' flag
let account = '0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1'
let privateKey = '4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d'

export { account, privateKey }
