
// this is the fist address generated by testrpc when run with the '--deterministic' flag
let address = '0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1'
let privateKey = '4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d'

let address1 = '0xffcf8fdee72ac11b5c542428b35eef5769c409f0'
let address99 = '0x0000000000000000000000000000000000000001'

export { address, address1, address99, privateKey }
